server:
  port: 8085
spring:
  datasource:
    url: jdbc:sqlserver://sqlsrvdatalayerdesa.database.windows.net;databaseName=sqlbddatalayerdesa;encrypt=false;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: usmagnadb
    password: M4gn4_2020+
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
magna:
  ids:
    products:
      metas: "006"
      pamayo: "007"
    status:
      active: "A"
    source-channel:
      web: "WEB"
    templates:
      agreement-metas: 27
      agreement-pamayo: 26
    conversation-registration:
      metas: "281383"
      pamayo: "281236"
    conversation-approval:
      metas: "282139"
      pamayo: "282093"
    conversation-rejection:
      metas: "281654"
      pamayo: "281648"
    conversation-cancel:
      metas: "285961"
      pamayo: "285714"
    conversation-update:
      metas: "287482"
      pamayo: "287493"
    type-core:
      debit: 40
    account:
      deposit: 2
  name:
    document:
      approved: "Acuerdo de aportes por Débito Automático.pdf"
    dana-var-config:
      automatic-debit-home: "AUTOMATIC_DEBIT"
      automatic-debit-agreement: "AutomaticDebitAgreementFile"
      share-affiliates: "affiliates"
      procedure-name-apvsf: "apvsf-opening"
    dana-var-content:
      first-name: "firstName"
      input: "Aporte"
      frequency: "Frecuencia"
      bank-account: "CuentaBancaria"
      bank-type: "TipoBanco"
  sp-mailing:
    url: http://10.105.9.152/sp-mailing/
  dm-affiliate-information:
    url: http://10.105.9.152/dm-affiliate-information/
  sp-document-generator:
    url: http://10.105.9.152/sp-document-generator/
  sp-document-manager:
    url: http://10.105.9.152/sp-document-manager/
  dm-affiliate-contact-info:
    url: http://10.105.9.152/dm-affiliate-contact-info/
  sp-parameter:
    url: http://10.105.9.152/sp-parameter/
apolo:
  documentation:
    enabled: true
    api:
      title: Automatic Debit Info
      description: API allows to obtain operations for Automatic Debit
      version: 1.0.0
  tracing:
    obfuscation:
      enabled: true
      base-sensitive-fields:
        - field: bankAccount